name: "Update flake.lock"
on:
  workflow_dispatch:

jobs:
  update-lock:
    name: lock
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixos-unstable
        env:
          NIX_CONFIG: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Update flake deps
        run: nix flake update
        env:
          NIX_CONFIG: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update flake.lock"
          branch: main